In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
with open(r"D:\Datamites_AI\Data Sets\task.txt", "r") as f:
    text = f.read()


In [3]:
text

'About the Program\nWhat is the course fee for  Data Science Mentorship Program (DSMP 2023)\nThe course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.\nWhat is the total duration of the course?\nThe total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)\nWhat is the syllabus of the mentorship program?\nWe will be covering the following modules:\nPython Fundamentals\nPython libraries for Data Science\nData Analysis\nSQL for Data Science\nMaths for Machine Learning\nML Algorithms\nPractical ML\nMLOPs\nCase studies\nYou can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390\nWill Deep Learning and NLP be a part of this program?\nNo, NLP and Deep Learning both are not a part of this program’s curriculum.\nWhat if I miss a live session? Will I get a recording of the session?\nYes all our sessions are recorded, so eve

In [4]:
text[:100]

'About the Program\nWhat is the course fee for  Data Science Mentorship Program (DSMP 2023)\nThe course'

In [5]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
tokenizer=Tokenizer()

In [7]:
tokenizer.fit_on_texts([text])

In [8]:
len(tokenizer.word_index)

282

In [ ]:
tokenizer.texts_to_sequences(text.split('\n'))

In [10]:
input_sequences=[]
for sentence in text.split('\n'):
    tokenized_sentences=tokenizer.texts_to_sequences([sentence])[0]

    for i in range(1,len(tokenized_sentences)):
        input_sequences.append(tokenized_sentences[:i+1])


In [ ]:
input_sequences

In [12]:
len(input_sequences)

863

In [13]:
max_len=max([len(x) for x in input_sequences])

In [14]:
max_len

57

In [15]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences=pad_sequences(input_sequences,maxlen=max_len,padding='pre')

In [16]:
padded_input_sequences

array([[  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,  93,   1,  13],
       [  0,   0,   0, ...,   0,  11,   7],
       ...,
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281],
       [  0,   0,   0, ..., 280, 281, 282]])

In [17]:
X=padded_input_sequences[:,:-1]
y=padded_input_sequences[:,-1]

In [18]:
X

array([[  0,   0,   0, ...,   0,   0,  93],
       [  0,   0,   0, ...,   0,  93,   1],
       [  0,   0,   0, ...,   0,   0,  11],
       ...,
       [  0,   0,   0, ...,   0, 279,  18],
       [  0,   0,   0, ..., 279,  18, 280],
       [  0,   0,   0, ...,  18, 280, 281]])

In [19]:
X.shape

(863, 56)

In [20]:
y.shape

(863,)

In [21]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=283)

In [22]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [25]:
model=Sequential()
model.add(Embedding(283,100,input_length=56,input_shape=(max_len,)))
model.add(LSTM(150,return_sequences=True))
model.add(LSTM(150))
model.add(Dense(283,activation='softmax'))

In [26]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 57, 100)        │        28,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 57, 150)        │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_3 (LSTM)                   │ (None, 150)            │       180,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 283)            │        42,733 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 402,233 (1.53 MB)

 Trainable params: 402,233 (1.53 MB)

 Non-trainable params: 0 (0.00 B)

In [28]:
model.fit(X,y,epochs=50)

Epoch 1/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 6s 71ms/step - accuracy: 0.0718 - loss: 5.3895
Epoch 2/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 71ms/step - accuracy: 0.0776 - loss: 5.0850
Epoch 3/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 74ms/step - accuracy: 0.0776 - loss: 5.0295
Epoch 4/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 6s 234ms/step - accuracy: 0.0776 - loss: 5.0093
Epoch 5/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - accuracy: 0.0776 - loss: 5.0184
Epoch 6/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 72ms/step - accuracy: 0.0776 - loss: 5.0027
Epoch 7/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 6s 233ms/step - accuracy: 0.0776 - loss: 4.9378
Epoch 8/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 79ms/step - accuracy: 0.0742 - loss: 4.8627
Epoch 9/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 129ms/step - accuracy: 0.0788 - loss: 4.7692
Epoch 10/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 164ms/step - accuracy: 0.0857 - loss: 4.6500
Epoch 11/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 194ms/step - accuracy: 0.0973 - loss: 4.5140
Epoch 12/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 91ms/step - accu

In [31]:
import time

def Next_WordPredictor(text_1):
    for i in range(10):
        token_text=tokenizer.texts_to_sequences([text_1])[0]
        padded_token_text=pad_sequences([token_text],maxlen=56,padding='pre')
        pos=np.argmax(model.predict(padded_token_text))
        for word,index in tokenizer.word_index.items():
            if index==pos:
                text_1=text_1+" "+word
                print(text_1)
                time.sleep(2)

In [32]:
text=input()
Next_WordPredictor(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 300ms/step
Maths one
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
Maths one is
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
Maths one is tricky
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Maths one is tricky read
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
Maths one is tricky read carefully
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
Maths one is tricky read carefully you
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
Maths one is tricky read carefully you can
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Maths one is tricky read carefully you can watch
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
Maths one is tricky read carefully you can watch the
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Maths one is tricky read carefully you can watch the payment


In [33]:
Next_WordPredictor("Data Science")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
Data Science for
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Data Science for data
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Data Science for data science
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
Data Science for data science science
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Data Science for data science science campusx
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
Data Science for data science science campusx program
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Data Science for data science science campusx program dsmp
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
Data Science for data science science campusx program dsmp 2023
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
Data Science for data science science campusx program dsmp 2023 2023
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
Data Science for data science science campusx program dsmp 2023 2023 a
